blackops:
  id: "blackops"
  label: "BlackOps"
  description: "Industrial, terminal-grade dark aesthetic."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - dark
    - industrial
    - monospaced
    - technical

redacted:
  id: "redacted"
  label: "Redacted"
  description: "Classified, blackout dossier aesthetic."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - dark
    - classified
    - censorship
    - document

ghost:
  id: "ghost"
  label: "Ghost Archive"
  description: "Corrupted, leaked archive aesthetic."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - dark
    - glitch
    - archive
    - degraded

cyberpunk:
  id: "cyberpunk"
  label: "Cyberpunk"
  description: "Neon-infused, retro-futuristic aesthetic with vibrant colors."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - neon
    - futuristic
    - vibrant
    - high-tech

noir:
  id: "noir"
  label: "Noir"
  description: "Classic film noir aesthetic with high contrast and dramatic shadows."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - monochrome
    - vintage
    - dramatic
    - high-contrast

vapor:
  id: "vapor"
  label: "Vaporwave"
  description: "Retro 80s/90s vaporwave aesthetic with pastel gradients and nostalgia."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - retro
    - pastel
    - gradient
    - nostalgic

terminal:
  id: "terminal"
  label: "Terminal"
  description: "Classic command-line aesthetic with green-on-black monospace styling."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - dark
    - monospaced
    - classic
    - command-line

matrix:
  id: "matrix"
  label: "Matrix"
  description: "Digital rain aesthetic with cascading characters and cyber atmosphere."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - dark
    - cyberpunk
    - animated
    - green

hologram:
  id: "hologram"
  label: "Hologram"
  description: "Futuristic holographic projection with blue glows and scan lines."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - futuristic
    - blue
    - sci-fi
    - glowing

parchment:
  id: "parchment"
  label: "Parchment"
  description: "Ancient manuscript aesthetic with aged paper and serif typography."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - vintage
    - serif
    - warm
    - historical

neon:
  id: "neon"
  label: "Neon"
  description: "Vibrant neon sign aesthetic with electric glowing borders."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - vibrant
    - glowing
    - colorful
    - urban

blueprint:
  id: "blueprint"
  label: "Blueprint"
  description: "Technical blueprint aesthetic with grid lines and engineering style."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - technical
    - blue
    - grid
    - engineering

synthwave:
  id: "synthwave"
  label: "Synthwave"
  description: "80s retrowave with sunset gradients and neon grid aesthetic."
  mediums:
    - markdown
    - css
    - pdf
  status: "stable"
  tags:
    - retro
    - gradient
    - neon
    - 80s
